goodhood-eu/goodhood

package-lock.json, package.json, packages/icons/.browserslistrc, packages/icons/package.json, packages/icons/preview/import_statements.jsx, packages/icons/preview/pages/list.jsx
https://favro.com/organization/aee06c3fe6503c804f507dd9/22c630cc02b09f2d6f98b8b3?card=Goo-29157
=> Add import statements to preview and improve icon-details navigation

packages/icons/package-lock.json, packages/icons/package.json, packages/icons/scripts/build.js, packages/icons/utils/naming.js
- svgr doesn't allow to specify plugins for overall babel (only for the jsx part - it is processed separately)
=> Icons: Build to commonjs instead esm

packages/icons/webpack.config.js
https://nebenan.slack.com/archives/CDH4A22PP/p1595842456000800
=> Fix icons preview (babel config resolution)

package-lock.json, package.json
https://favro.com/organization/aee06c3fe6503c804f507dd9/22c630cc02b09f2d6f98b8b3?card=Goo-31500
=> eslint-config-nebenan-2.0.0

packages/components/package-lock.json, packages/components/package.json, packages/components/src/cookies_banner/index.module.scss
https://jira.nebenan.de/browse/CORE-5845?focusedCommentId=25954&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25954
=> Change CookieBanner z-index to prevent overlapping with other components

package.json, presets/react/rollup.config.js
https://favro.com/organization/aee06c3fe6503c804f507dd9/22c630cc02b09f2d6f98b8b3?card=Goo-32133
Previously: `packages/map/lib/index.css + packages/map/styles.css`
Now: `packages/map/styles.css`
=> Fix issue with duplicate css files in packages

packages/components/package-lock.json, packages/components/package.json, packages/components/src/reaction_selection_menu/index.module.scss
https://jira.nebenan.de/browse/CORE-6087?focusedCommentId=26073&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26073
=> Fix z-index of ReactionSelectionMenu popover

packages/components/package.json, packages/components/src/reaction_selection_menu/constants.jsx, packages/components/src/reaction_selection_menu/hooks.jsx, packages/components/src/reaction_selection_menu/utils.jsx, packages/components/src/reaction_selection_menu/utils.test.jsx
https://jira.nebenan.de/browse/CORE-6278
=> Fix accidental shortTap when user tries to scroll

.browserslistrc
https://favro.com/organization/aee06c3fe6503c804f507dd9/22c630cc02b09f2d6f98b8b3?card=Goo-31417
=> Change browserslist to cover more browsers

packages/components/package-lock.json, packages/components/package.json, packages/components/src/network_form/hooks.jsx, packages/components/src/network_form/index.jsx, packages/components/src/network_form/index.stories.jsx, packages/components/src/network_form/utils.jsx, packages/components/src/network_form/utils.test.jsx
https://favro.com/organization/aee06c3fe6503c804f507dd9/22c630cc02b09f2d6f98b8b3?card=Goo-30677
=> Components: Add NetworkForm

packages/components/package-lock.json, packages/components/package.json, packages/components/src/link_header/index.jsx, packages/components/src/link_header/index.module.scss, packages/components/src/link_header/index.stories.jsx
Added the new `label` prop because I need to build this:
=> Add LinkHeader and add new label prop

packages/components/package.json, packages/components/src/image_zoom_provider/hooks.jsx
https://favro.com/organization/aee06c3fe6503c804f507dd9/22c630cc02b09f2d6f98b8b3?card=Goo-38932
=> Add guard conditions for ImageZoomViews with dead images

packages/map/package-lock.json, packages/map/package.json, packages/map/src/popup/index.jsx, packages/map/src/popup/index.module.scss
https://github.com/good-hood-gmbh/nebenan-frontend/pull/1313/files#r611775106
=> Map: Add fancy popup styling

packages/modals/package.json, packages/modals/src/alert/index.jsx
https://jira.nebenan.de/browse/CORE-8048 & https://jira.nebenan.de/browse/CORE-8049
=> [CORE-8048, CORE-8049] fix Alert component to support footer button

packages/modals/CHANGELOG.md, packages/modals/package.json, packages/modals/src/illustration_modal/index.module.scss, packages/modals/src/modal/index.jsx, packages/modals/src/modal/index.module.scss, packages/modals/src/modal/index.stories.jsx, packages/modals/src/modal/index.stories.module.scss, packages/modals/src/scrollable_modal/index.jsx, packages/modals/src/scrollable_modal/index.module.scss, packages/modals/src/scrollable_modal/index.stories.jsx
https://jira.nebenan.de/browse/CORE-8062?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
- Makes normal modals scrollable
- Makes the content section in ScrollableModals scrollable
- Fixes static positioning
=> Modal: Fix scrolling behavior

packages/chargebee/README.md, packages/chargebee/src/checkout/index.jsx, packages/chargebee/src/checkout/index.stories.jsx, packages/chargebee/src/constants/index.jsx
Added callbacks for checkout-loaded and checkout-step to the chargebee checkout component
=> Callbacks for chargebee checkout-loaded and checkout-step

packages/components/package.json, packages/components/src/ecosystem_bar/hooks.jsx, packages/components/src/ecosystem_bar/index.jsx, packages/components/src/ecosystem_bar/index.module.scss, packages/components/src/ecosystem_bar/index.stories.jsx
See [Jira Link](https://jira.nebenan.de/browse/CORE-8559)
**Notes**
- We found out that we have to keep menu items inside of projects and pass as a prop, because we don’t want to implement anything translation related into goodhood
- Therefore we chose to introduce an new prop `items`
=> [CORE-8559] Add new ecosystem bar

packages/components/package.json, packages/components/src/ecosystem_bar/index.jsx, packages/components/src/ecosystem_bar/index.stories.jsx
Add text to item object so it's more clear what we are doing there.
=> Change structure of items in ecosystem navbar

.preview/src/containers/story/index.jsx, .preview/src/modules/stories/index.jsx, packages/modals/package.json, packages/modals/src/modal/scroll_lock.stories.jsx, packages/modals/src/modal/scroll_lock.stories.module.scss, packages/modals/src/provider/hooks.jsx
[JIRA](https://jira.nebenan.de/browse/CORE-8418)
Issue:
- Render modal a
- Scroll gets locked
- Content gets pushed down since modal is always rendered on the very top of the page
- Render modal b
- Modal a is unmounted, scrolling position is restored
- ???
=> [CORE-8418] Fix bad scroll lock for sequence of modals

packages/components/package.json, packages/components/src/reactions_row/index.jsx, packages/components/src/reactions_row/index.stories.jsx
Introduce possibility to show the number 0 instead of returning null.
=> [CORE-9235] Introduce showNull prop to <ReactionsRow>

packages/map/package.json, packages/map/src/pin_marker/index.stories.jsx, yarn.lock
https://jira.nebenan.de/browse/CORE-9769
=> [CORE-9769] Maps: Update to maplibre-gl v2

packages/components/package.json, packages/components/src/feature_alert/index.module.scss
[JIRA](https://jira.nebenan.de/browse/CORE-10022)
=> [CORE-10022] Fixed tooltip arrow

packages/inputs-minimal/package.json, packages/inputs-minimal/src/textfield/index.jsx, packages/inputs-minimal/src/textfields_meta/index.jsx, packages/inputs-minimal/src/textfields_meta/index.module.scss
Relates to https://github.com/good-hood-gmbh/nebenan-frontend/pull/1718
=> [CORE-10707] Refactor TextFieldMeta component to support FieldGroup

packages/inputs-minimal/package.json, packages/inputs-minimal/src/password_field/index.stories.jsx, packages/inputs-minimal/src/textfield/index.jsx, packages/inputs-minimal/src/textfield/index.module.scss, packages/inputs-minimal/src/textfield/use_autofill.jsx, packages/inputs-minimal/src/textfield/use_autofill.module.scss
[https://jira.nebenan.de/browse/CORE-10326](https://jira.nebenan.de/browse/CORE-10326)
=> [CORE-10326] Autofill with presaved passwords breaks design on /login page

packages/map/CHANGELOG.md, packages/map/package.json, yarn.lock
fixed in 2.1.8-pre.2 of maplibre-gl-js
see https://github.com/maplibre/maplibre-gl-js/pull/1099
=> [CORE-11289] Fix "undefined source cashes"

packages/inputs-minimal/package.json, packages/inputs-minimal/src/select/index.module.scss, packages/inputs-minimal/src/textarea/index.module.scss, packages/inputs-minimal/src/textfield/index.module.scss, packages/inputs-minimal/src/textfields_meta/index.module.scss, yarn.lock
[JIRA Link](https://jira.nebenan.de/browse/CORE-10528)
=> [CORE-10528] Fix error color for input fields

package.json, packages/chargebee/package.json, packages/components/package.json, packages/inputs-minimal/package.json, packages/map/package.json, packages/modals/package.json, packages/tracking/package.json, presets/react/rollup.config.js, yarn.lock
Reviewer: Please check the generated bundles. Now all the listed peer deps and deps should show up as require/import statements
=> Fix externals in rollup config

package.json, packages/components/package.json, yarn.lock
to get rid of that lodash monolith import in core
=> Cleanup dependencies

packages/icons/package.json, packages/icons/scripts/build.js, packages/icons/svgo.config.js, packages/icons/tsconfig.json, packages/icons/webpack.config.js
We need all our exports as commonjs. Previously we had esmodules in there
=> Icons: Fix typescript setup

packages/tracking/package.json, yarn.lock
not much to do besides cleaning up the dependencies
=> CORE-11326 Convert tracking to React18

packages/inputs-minimal/package.json, packages/inputs-minimal/src/password_field/index.jsx, packages/modals/package.json, yarn.lock
[Jira Link](https://jira.nebenan.de/browse/CORE-12555)
=> Update inputs-minimal to React 18

packages/modals/package.json, yarn.lock
[Jira Link](https://jira.nebenan.de/browse/CORE-12557)
=> Update goodhood/modals to React 18

packages/components/package.json, packages/components/src/ecosystem_bar/index.stories.jsx, yarn.lock
[JIRA Link](https://jira.nebenan.de/browse/CORE-11326)
Update packages/components to support React 18
=> Update @goodhood/components to react 18

packages/tracking/package.json, packages/tracking/src/hooks/use_track.ts, packages/tracking/src/hooks/use_track_page_view.ts, packages/tracking/src/types.ts
[JIRA Link CORE-13349](https://jira.nebenan.de/browse/CORE-13349)
[JIRA Link CORE-13386](https://jira.nebenan.de/browse/CORE-13386)
[JIRA Link CORE-13389](https://jira.nebenan.de/browse/CORE-13389)
[JIRA Link CORE-13390](https://jira.nebenan.de/browse/CORE-13390)
**Definition of Done**
**Road to Merge**
=> Tracking Updates

packages/tracking/package.json, packages/tracking/src/types.ts, yarn.lock
fixes typescript warnings in our core ts checks
=> Make filter_category type optional

packages/tracking/package.json, packages/tracking/src/types.ts
Added field in the type is needed for [this](https://jira.nebenan.de/browse/CORE-13495) ticket
=> CORE-13495: updates ClickEvent type

packages/tracking/webflow/webflow_ga_tracking_snippet.js
We will use this snippet to provide custom GA events for Webflow pages.
It will be served as is and added to Webflow pages via webflow UI.
=> CORE-13233: adds tracking snippet to the repo

packages/map/package.json, yarn.lock
to fix safari error with webgl2
=> [CORE-13688] Bump maplibre version

packages/tracking/package.json, packages/tracking/src/hooks/use_track.ts, packages/tracking/src/types.ts
[Jira link](https://jira.nebenan.de/browse/CORE-13108)
Adds events from [this](https://wiki.nebenan.de/display/PROD/Value+guide+-+ecommerce) guide
=> CORE-13108: ecommerce tracking

packages/tracking/package.json, packages/tracking/src/types.ts
[Jira link](https://jira.nebenan.de/browse/CORE-13233)
Finalising events types
=> [CORE-13108]: e commerce tracking

packages/tracking/package.json, packages/tracking/src/types.ts
[Jira link](https://jira.nebenan.de/browse/CORE-13704)
=> CORE-13704: post detail page tracking name
